<?php

namespace ContainerXaSGAQg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShoppinglistPostProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\ShoppinglistPostProcessor' shared autowired service.
     *
     * @return \App\State\ShoppinglistPostProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/ShoppinglistPostProcessor.php';

        return $container->privates['App\\State\\ShoppinglistPostProcessor'] = new \App\State\ShoppinglistPostProcessor(($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')));
    }
}
